import Image1 from "../src/assets/pro1.jpg";
import Image2 from "../src/assets/pro2.png";
import Image3 from "../src/assets/pro3.png";
import Image4 from "../src/assets/pro4.png";
import Image5 from "../src/assets/pro5.png";
import Image6 from "../src/assets/pro6.png";
import Image7 from "../src/assets/pro7.png";
import Image8 from "../src/assets/pro8.png";
import Image9 from "../src/assets/pro9.png";
import Image10 from "../src/assets/pro12.png";
import Image11 from "../src/assets/pro11.png";
import Image12 from "../src/assets/pro12.png";

let data = [
  {
    id: 1,
    title: "Basic Crew Neck Tee",
    price: "44.00",
    colorType: "Black",
    image: Image1,
    addWishList: "Add to Wish List",
    compare: "Compare",
    addCart: "Add to Cart",
    badge: "New",
  },
  {
    id: 1,
    title: "Basic Crew Neck Tee",
    price: "44.00",
    colorType: "Black",
    image: Image1,
    addWishList: "Add to Wish List",
    compare: "Compare",
    addCart: "Add to Cart",
    badge: "New",
  },
  {
    id: 1,
    title: "Basic Crew Neck Tee",
    price: "44.00",
    colorType: "Black",
    image: Image1,
    addWishList: "Add to Wish List",
    compare: "Compare",
    addCart: "Add to Cart",
    badge: "New",
  },
  {
    id: 1,
    title: "Basic Crew Neck Tee",
    price: "44.00",
    colorType: "Black",
    image: Image1,
    addWishList: "Add to Wish List",
    compare: "Compare",
    addCart: "Add to Cart",
    badge: "New",
  },
  {
    id: 1,
    title: "Basic Crew Neck Tee",
    price: "44.00",
    colorType: "Black",
    image: Image1,
    addWishList: "Add to Wish List",
    compare: "Compare",
    addCart: "Add to Cart",
    badge: "New",
  },
  {
    id: 2,
    title: "Basic Crew Neck Tee",
    price: "440.00",
    colorType: "Black",
    image: Image2,
    addWishList: "Add to Wish List",
    compare: "Compare",
    addCart: "Add to Cart",
    badge: "New",
  },
  {
    id: 3,
    title: "Basic Crew Neck Tee",
    price: "449.00",
    colorType: "Black",
    image: Image3,
    addWishList: "Add to Wish List",
    compare: "Compare",
    addCart: "Add to Cart",
    badge: "New",
  },
  {
    id: 4,
    title: "Basic Crew Neck Tee",
    price: "434.00",
    colorType: "Black",
    image: Image4,
    addWishList: "Add to Wish List",
    compare: "Compare",
    addCart: "Add to Cart",
    badge: "New",
  },
  {
    id: 5,
    title: "Basic Crew Neck Tee",
    price: "454.00",
    colorType: "Black",
    image: Image5,
    addWishList: "Add to Wish List",
    compare: "Compare",
    addCart: "Add to Cart",
    badge: "New",
  },
  {
    id: 6,
    title: "Basic Crew Neck Tee",
    price: "404.00",
    colorType: "Black",
    image: Image6,
    addWishList: "Add to Wish List",
    compare: "Compare",
    addCart: "Add to Cart",
    badge: "New",
  },
  {
    id: 7,
    title: "Basic Crew Neck Tee",
    price: "4400.00",
    colorType: "Black",
    image: Image7,
    addWishList: "Add to Wish List",
    compare: "Compare",
    addCart: "Add to Cart",
    badge: "New",
  },
  {
    id: 8,
    title: "Basic Crew Neck Tee",
    price: "440.00",
    colorType: "Black",
    image: Image3,
    addWishList: "Add to Wish List",
    compare: "Compare",
    addCart: "Add to Cart",
    badge: "New",
  },
  {
    id: 9,
    title: "Basic Crew Neck Tee",
    price: "544.00",
    colorType: "Black",
    image: Image4,
    addWishList: "Add to Wish List",
    compare: "Compare",
    addCart: "Add to Cart",
    badge: "New",
  },
  {
    id: 10,
    title: "Basic Crew Neck Tee",
    price: "644.00",
    colorType: "Black",
    image: Image8,
    addWishList: "Add to Wish List",
    compare: "Compare",
    addCart: "Add to Cart",
    badge: "New",
  },
  {
    id: 11,
    title: "Basic Crew Neck Tee",
    price: "9944.00",
    colorType: "Black",
    image: Image9,
    addWishList: "Add to Wish List",
    compare: "Compare",
    addCart: "Add to Cart",
    badge: "New",
  },
  {
    id: 12,
    title: "Basic Crew Neck Tee",
    price: "344.00",
    colorType: "Black",
    image: Image7,
    addWishList: "Add to Wish List",
    compare: "Compare",
    addCart: "Add to Cart",
    badge: "New",
  },
  {
    id: 6,
    title: "Basic Crew Neck Tee",
    price: "89944.00",
    colorType: "Black",
    image: Image6,
    addWishList: "Add to Wish List",
    compare: "Compare",
    addCart: "Add to Cart",
    badge: "New",
  },
  {
    id: 7,
    title: "Basic Crew Neck Tee",
    price: "2344.00",
    colorType: "Black",
    image: Image7,
    addWishList: "Add to Wish List",
    compare: "Compare",
    addCart: "Add to Cart",
    badge: "New",
  },
  {
    id: 8,
    title: "Basic Crew Neck Tee",
    price: "2144.00",
    colorType: "Black",
    image: Image3,
    addWishList: "Add to Wish List",
    compare: "Compare",
    addCart: "Add to Cart",
    badge: "New",
  },
  {
    id: 1,
    title: "Basic Crew Neck Tee",
    price: "744.00",
    colorType: "Black",
    image: Image1,
    addWishList: "Add to Wish List",
    compare: "Compare",
    addCart: "Add to Cart",
    badge: "New",
  },
  {
    id: 2,
    title: "Basic Crew Neck Tee",
    price: "744.00",
    colorType: "Black",
    image: Image2,
    addWishList: "Add to Wish List",
    compare: "Compare",
    addCart: "Add to Cart",
    badge: "New",
  },
  {
    id: 3,
    title: "Basic Crew Neck Tee",
    price: "544.00",
    colorType: "Black",
    image: Image3,
    addWishList: "Add to Wish List",
    compare: "Compare",
    addCart: "Add to Cart",
    badge: "New",
  },
  {
    id: 4,
    title: "Basic Crew Neck Tee",
    price: "944.00",
    colorType: "Black",
    image: Image4,
    addWishList: "Add to Wish List",
    compare: "Compare",
    addCart: "Add to Cart",
    badge: "New",
  },
  {
    id: 5,
    title: "Basic Crew Neck Tee",
    price: "444.00",
    colorType: "Black",
    image: Image5,
    addWishList: "Add to Wish List",
    compare: "Compare",
    addCart: "Add to Cart",
    badge: "New",
  },
  {
    id: 6,
    title: "Basic Crew Neck Tee",
    price: "544.00",
    colorType: "Black",
    image: Image6,
    addWishList: "Add to Wish List",
    compare: "Compare",
    addCart: "Add to Cart",
    badge: "New",
  },
  {
    id: 7,
    title: "Basic Crew Neck Tee",
    price: "7644.00",
    colorType: "Black",
    image: Image7,
    addWishList: "Add to Wish List",
    compare: "Compare",
    addCart: "Add to Cart",
    badge: "New",
  },
  {
    id: 8,
    title: "Basic Crew Neck Tee",
    price: "4544.00",
    colorType: "Black",
    image: Image3,
    addWishList: "Add to Wish List",
    compare: "Compare",
    addCart: "Add to Cart",
    badge: "New",
  },
  {
    id: 6,
    title: "Basic Crew Neck Tee",
    price: "8944.00",
    colorType: "Black",
    image: Image6,
    addWishList: "Add to Wish List",
    compare: "Compare",
    addCart: "Add to Cart",
    badge: "New",
  },
  {
    id: 7,
    title: "Basic Crew Neck Tee",
    price: "6744.00",
    colorType: "Black",
    image: Image7,
    addWishList: "Add to Wish List",
    compare: "Compare",
    addCart: "Add to Cart",
    badge: "New",
  },
  {
    id: 8,
    title: "Basic Crew Neck Tee",
    price: "6744.00",
    colorType: "Black",
    image: Image3,
    addWishList: "Add to Wish List",
    compare: "Compare",
    addCart: "Add to Cart",
    badge: "New",
  },
  {
    id: 6,
    title: "Basic Crew Neck Tee",
    price: "744.00",
    colorType: "Black",
    image: Image6,
    addWishList: "Add to Wish List",
    compare: "Compare",
    addCart: "Add to Cart",
    badge: "New",
  },
  {
    id: 7,
    title: "Basic Crew Neck Tee",
    price: "7844.00",
    colorType: "Black",
    image: Image7,
    addWishList: "Add to Wish List",
    compare: "Compare",
    addCart: "Add to Cart",
    badge: "New",
  },
  {
    id: 8,
    title: "Basic Crew Neck Tee",
    price: "6844.00",
    colorType: "Black",
    image: Image3,
    addWishList: "Add to Wish List",
    compare: "Compare",
    addCart: "Add to Cart",
    badge: "New",
  },
  {
    id: 6,
    title: "Basic Crew Neck Tee",
    price: "76744.00",
    colorType: "Black",
    image: Image6,
    addWishList: "Add to Wish List",
    compare: "Compare",
    addCart: "Add to Cart",
    badge: "New",
  },
  {
    id: 7,
    title: "Basic Crew Neck Tee",
    price: "65444.00",
    colorType: "Black",
    image: Image7,
    addWishList: "Add to Wish List",
    compare: "Compare",
    addCart: "Add to Cart",
    badge: "New",
  },
  {
    id: 8,
    title: "Basic Crew Neck Tee",
    price: "8744.00",
    colorType: "Black",
    image: Image3,
    addWishList: "Add to Wish List",
    compare: "Compare",
    addCart: "Add to Cart",
    badge: "New",
  },
  {
    id: 6,
    title: "Basic Crew Neck Tee",
    price: "644.00",
    colorType: "Black",
    image: Image6,
    addWishList: "Add to Wish List",
    compare: "Compare",
    addCart: "Add to Cart",
    badge: "New",
  },
  {
    id: 7,
    title: "Basic Crew Neck Tee",
    price: "76844.00",
    colorType: "Black",
    image: Image7,
    addWishList: "Add to Wish List",
    compare: "Compare",
    addCart: "Add to Cart",
    badge: "New",
  },
  {
    id: 8,
    title: "Basic Crew Neck Tee",
    price: "345444.00",
    colorType: "Black",
    image: Image3,
    addWishList: "Add to Wish List",
    compare: "Compare",
    addCart: "Add to Cart",
    badge: "New",
  },
  {
    id: 1,
    title: "Basic Crew Neck Tee",
    price: "56744.00",
    colorType: "Black",
    image: Image1,
    addWishList: "Add to Wish List",
    compare: "Compare",
    addCart: "Add to Cart",
    badge: "New",
  },
  {
    id: 2,
    title: "Basic Crew Neck Tee",
    price: "544.00",
    colorType: "Black",
    image: Image2,
    addWishList: "Add to Wish List",
    compare: "Compare",
    addCart: "Add to Cart",
    badge: "New",
  },
  {
    id: 3,
    title: "Basic Crew Neck Tee",
    price: "4644.00",
    colorType: "Black",
    image: Image3,
    addWishList: "Add to Wish List",
    compare: "Compare",
    addCart: "Add to Cart",
    badge: "New",
  },
  {
    id: 4,
    title: "Basic Crew Neck Tee",
    price: "89844.00",
    colorType: "Black",
    image: Image4,
    addWishList: "Add to Wish List",
    compare: "Compare",
    addCart: "Add to Cart",
    badge: "New",
  },
  {
    id: 5,
    title: "Basic Crew Neck Tee",
    price: "8744.00",
    colorType: "Black",
    image: Image5,
    addWishList: "Add to Wish List",
    compare: "Compare",
    addCart: "Add to Cart",
    badge: "New",
  },
  {
    id: 6,
    title: "Basic Crew Neck Tee",
    price: "76844.00",
    colorType: "Black",
    image: Image6,
    addWishList: "Add to Wish List",
    compare: "Compare",
    addCart: "Add to Cart",
    badge: "New",
  },
  {
    id: 1,
    title: "Basic Crew Neck Tee",
    price: "7844.00",
    colorType: "Black",
    image: Image1,
    addWishList: "Add to Wish List",
    compare: "Compare",
    addCart: "Add to Cart",
    badge: "New",
  },
  {
    id: 2,
    title: "Basic Crew Neck Tee",
    price: "80944.00",
    colorType: "Black",
    image: Image2,
    addWishList: "Add to Wish List",
    compare: "Compare",
    addCart: "Add to Cart",
    badge: "New",
  },
  {
    id: 3,
    title: "Basic Crew Neck Tee",
    price: "944.00",
    colorType: "Black",
    image: Image3,
    addWishList: "Add to Wish List",
    compare: "Compare",
    addCart: "Add to Cart",
    badge: "New",
  },
  {
    id: 4,
    title: "Basic Crew Neck Tee",
    price: "244.00",
    colorType: "Black",
    image: Image12,
    addWishList: "Add to Wish List",
    compare: "Compare",
    addCart: "Add to Cart",
    badge: "New",
  },
  {
    id: 5,
    title: "Basic Crew Neck Tee",
    price: "44.00",
    colorType: "Black",
    image: Image5,
    addWishList: "Add to Wish List",
    compare: "Compare",
    addCart: "Add to Cart",
    badge: "New",
  },
  {
    id: 7,
    title: "Basic Crew Neck Tee",
    price: "144.00",
    colorType: "Black",
    image: Image7,
    addWishList: "Add to Wish List",
    compare: "Compare",
    addCart: "Add to Cart",
    badge: "New",
  },
  {
    id: 8,
    title: "Basic Crew Neck Tee",
    price: "244.00",
    colorType: "Black",
    image: Image3,
    addWishList: "Add to Wish List",
    compare: "Compare",
    addCart: "Add to Cart",
    badge: "New",
  },
  {
    id: 6,
    title: "Basic Crew Neck Tee",
    price: "74.00",
    colorType: "Black",
    image: Image6,
    addWishList: "Add to Wish List",
    compare: "Compare",
    addCart: "Add to Cart",
    badge: "New",
  },
  {
    id: 7,
    title: "Basic Crew Neck Tee",
    price: "94.00",
    colorType: "Black",
    image: Image7,
    addWishList: "Add to Wish List",
    compare: "Compare",
    addCart: "Add to Cart",
    badge: "New",
  },
  {
    id: 8,
    title: "Basic Crew Neck Tee",
    price: "504.00",
    colorType: "Black",
    image: Image3,
    addWishList: "Add to Wish List",
    compare: "Compare",
    addCart: "Add to Cart",
    badge: "New",
  },
  {
    id: 1,
    title: "Basic Crew Neck Tee",
    price: "200.00",
    colorType: "Black",
    image: Image1,
    addWishList: "Add to Wish List",
    compare: "Compare",
    addCart: "Add to Cart",
    badge: "New",
  },
  {
    id: 2,
    title: "Basic Crew Neck Tee",
    price: "30.00",
    colorType: "Black",
    image: Image2,
    addWishList: "Add to Wish List",
    compare: "Compare",
    addCart: "Add to Cart",
    badge: "New",
  },
  {
    id: 3,
    title: "Basic Crew Neck Tee",
    price: "90.00",
    colorType: "Black",
    image: Image3,
    addWishList: "Add to Wish List",
    compare: "Compare",
    addCart: "Add to Cart",
    badge: "New",
  },
  {
    id: 4,
    title: "Basic Crew Neck Tee",
    price: "100.00",
    colorType: "Black",
    image: Image4,
    addWishList: "Add to Wish List",
    compare: "Compare",
    addCart: "Add to Cart",
    badge: "New",
  },
  {
    id: 5,
    title: "Basic Crew Neck Tee",
    price: "80.00",
    colorType: "Black",
    image: Image12,
    addWishList: "Add to Wish List",
    compare: "Compare",
    addCart: "Add to Cart",
    badge: "New",
  },
  {
    id: 6,
    title: "Basic Crew Neck Tee",
    price: "98.00",
    colorType: "Black",
    image: Image6,
    addWishList: "Add to Wish List",
    compare: "Compare",
    addCart: "Add to Cart",
    badge: "New",
  },
  {
    id: 7,
    title: "Basic Crew Neck Tee",
    price: "99.00",
    colorType: "Black",
    image: Image7,
    addWishList: "Add to Wish List",
    compare: "Compare",
    addCart: "Add to Cart",
    badge: "New",
  },
  {
    id: 8,
    title: "Basic Crew Neck Tee",
    price: "234.00",
    colorType: "Black",
    image: Image3,
    addWishList: "Add to Wish List",
    compare: "Compare",
    addCart: "Add to Cart",
    badge: "New",
  },
  {
    id: 1,
    title: "Basic Crew Neck Tee",
    price: "94.00",
    colorType: "Black",
    image: Image1,
    addWishList: "Add to Wish List",
    compare: "Compare",
    addCart: "Add to Cart",
    badge: "New",
  },
  {
    id: 2,
    title: "Basic Crew Neck Tee",
    price: "74.00",
    colorType: "Black",
    image: Image11,
    addWishList: "Add to Wish List",
    compare: "Compare",
    addCart: "Add to Cart",
    badge: "New",
  },
  {
    id: 3,
    title: "Basic Crew Neck Tee",
    price: "24.00",
    colorType: "Black",
    image: Image3,
    addWishList: "Add to Wish List",
    compare: "Compare",
    addCart: "Add to Cart",
    badge: "New",
  },
  {
    id: 4,
    title: "Basic Crew Neck Tee",
    price: "34.00",
    colorType: "Black",
    image: Image4,
    addWishList: "Add to Wish List",
    compare: "Compare",
    addCart: "Add to Cart",
    badge: "New",
  },
  {
    id: 5,
    title: "Basic Crew Neck Tee",
    price: "84.00",
    colorType: "Black",
    image: Image5,
    addWishList: "Add to Wish List",
    compare: "Compare",
    addCart: "Add to Cart",
    badge: "New",
  },
  {
    id: 7,
    title: "Basic Crew Neck Tee",
    price: "974.00",
    colorType: "Black",
    image: Image7,
    addWishList: "Add to Wish List",
    compare: "Compare",
    addCart: "Add to Cart",
    badge: "New",
  },
  {
    id: 8,
    title: "Basic Crew Neck Tee",
    price: "436584.00",
    colorType: "Black",
    image: Image3,
    addWishList: "Add to Wish List",
    compare: "Compare",
    addCart: "Add to Cart",
    badge: "New",
  },
  {
    id: 6,
    title: "Basic Crew Neck Tee",
    price: "6754.00",
    colorType: "Black",
    image: Image6,
    addWishList: "Add to Wish List",
    compare: "Compare",
    addCart: "Add to Cart",
    badge: "New",
  },
  {
    id: 7,
    title: "Basic Crew Neck Tee",
    price: "754.00",
    colorType: "Black",
    image: Image7,
    addWishList: "Add to Wish List",
    compare: "Compare",
    addCart: "Add to Cart",
    badge: "New",
  },
  {
    id: 8,
    title: "Basic Crew Neck Tee",
    price: "5644.00",
    colorType: "Black",
    image: Image10,
    addWishList: "Add to Wish List",
    compare: "Compare",
    addCart: "Add to Cart",
    badge: "New",
  },
  {
    id: 1,
    title: "Basic Crew Neck Tee",
    price: "5674.00",
    colorType: "Black",
    image: Image1,
    addWishList: "Add to Wish List",
    compare: "Compare",
    addCart: "Add to Cart",
    badge: "New",
  },
  {
    id: 2,
    title: "Basic Crew Neck Tee",
    price: "8654.00",
    colorType: "Black",
    image: Image2,
    addWishList: "Add to Wish List",
    compare: "Compare",
    addCart: "Add to Cart",
    badge: "New",
  },
  {
    id: 3,
    title: "Basic Crew Neck Tee",
    price: "864.00",
    colorType: "Black",
    image: Image3,
    addWishList: "Add to Wish List",
    compare: "Compare",
    addCart: "Add to Cart",
    badge: "New",
  },
  {
    id: 4,
    title: "Basic Crew Neck Tee",
    price: "784.00",
    colorType: "Black",
    image: Image4,
    addWishList: "Add to Wish List",
    compare: "Compare",
    addCart: "Add to Cart",
    badge: "New",
  },
  {
    id: 5,
    title: "Basic Crew Neck Tee",
    price: "784.00",
    colorType: "Black",
    image: Image5,
    addWishList: "Add to Wish List",
    compare: "Compare",
    addCart: "Add to Cart",
    badge: "New",
  },
  {
    id: 6,
    title: "Basic Crew Neck Tee",
    price: "974.00",
    colorType: "Black",
    image: Image12,
    addWishList: "Add to Wish List",
    compare: "Compare",
    addCart: "Add to Cart",
    badge: "New",
  },
  {
    id: 7,
    title: "Basic Crew Neck Tee",
    price: "694.00",
    colorType: "Black",
    image: Image7,
    addWishList: "Add to Wish List",
    compare: "Compare",
    addCart: "Add to Cart",
    badge: "New",
  },
  {
    id: 8,
    title: "Basic Crew Neck Tee",
    price: "254.00",
    colorType: "Black",
    image: Image3,
    addWishList: "Add to Wish List",
    compare: "Compare",
    addCart: "Add to Cart",
    badge: "New",
  },
  {
    id: 6,
    title: "Basic Crew Neck Tee",
    price: "234.00",
    colorType: "Black",
    image: Image6,
    addWishList: "Add to Wish List",
    compare: "Compare",
    addCart: "Add to Cart",
    badge: "New",
  },
  {
    id: 7,
    title: "Basic Crew Neck Tee",
    price: "434.00",
    colorType: "Black",
    image: Image11,
    addWishList: "Add to Wish List",
    compare: "Compare",
    addCart: "Add to Cart",
    badge: "New",
  },
  {
    id: 8,
    title: "Basic Crew Neck Tee",
    price: "654.00",
    colorType: "Black",
    image: Image3,
    addWishList: "Add to Wish List",
    compare: "Compare",
    addCart: "Add to Cart",
    badge: "New",
  },
  {
    id: 6,
    title: "Basic Crew Neck Tee",
    price: "94.00",
    colorType: "Black",
    image: Image6,
    addWishList: "Add to Wish List",
    compare: "Compare",
    addCart: "Add to Cart",
    badge: "New",
  },
  {
    id: 7,
    title: "Basic Crew Neck Tee",
    price: "124.00",
    colorType: "Black",
    image: Image7,
    addWishList: "Add to Wish List",
    compare: "Compare",
    addCart: "Add to Cart",
    badge: "New",
  },
  {
    id: 8,
    title: "Basic Crew Neck Tee",
    price: "594.00",
    colorType: "Black",
    image: Image3,
    addWishList: "Add to Wish List",
    compare: "Compare",
    addCart: "Add to Cart",
    badge: "New",
  },
  {
    id: 6,
    title: "Basic Crew Neck Tee",
    price: "104.00",
    colorType: "Black",
    image: Image6,
    addWishList: "Add to Wish List",
    compare: "Compare",
    addCart: "Add to Cart",
    badge: "New",
  },
  {
    id: 7,
    title: "Basic Crew Neck Tee",
    price: "904.00",
    colorType: "Black",
    image: Image7,
    addWishList: "Add to Wish List",
    compare: "Compare",
    addCart: "Add to Cart",
    badge: "New",
  },
  {
    id: 8,
    title: "Basic Crew Neck Tee",
    price: "214.00",
    colorType: "Black",
    image: Image3,
    addWishList: "Add to Wish List",
    compare: "Compare",
    addCart: "Add to Cart",
    badge: "New",
  },
  {
    id: 6,
    title: "Basic Crew Neck Tee",
    price: "134.00",
    colorType: "Black",
    image: Image6,
    addWishList: "Add to Wish List",
    compare: "Compare",
    addCart: "Add to Cart",
    badge: "New",
  },
  {
    id: 7,
    title: "Basic Crew Neck Tee",
    price: "104.00",
    colorType: "Black",
    image: Image7,
    addWishList: "Add to Wish List",
    compare: "Compare",
    addCart: "Add to Cart",
    badge: "New",
  },
  {
    id: 8,
    title: "Basic Crew Neck Tee",
    price: "194.00",
    colorType: "Black",
    image: Image10,
    addWishList: "Add to Wish List",
    compare: "Compare",
    addCart: "Add to Cart",
    badge: "New",
  },
  {
    id: 6,
    title: "Basic Crew Neck Tee",
    price: "184.00",
    colorType: "Black",
    image: Image6,
    addWishList: "Add to Wish List",
    compare: "Compare",
    addCart: "Add to Cart",
    badge: "New",
  },
];

export default data;
